server {
  listen 8081;
  server_name _;

  proxy_read_timeout 3600;
  proxy_send_timeout 3600;

  location / {
    # Guacamole no contêiner "guacamole" na rede interna
    # Mantém o caminho original (/guacamole/...) sem duplicar o sufixo
    proxy_pass http://guacamole:8080/;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # Liberar embed em iframe apenas para o domínio do Nextcloud
    proxy_hide_header X-Frame-Options;
    proxy_hide_header Content-Security-Policy;
    add_header X-Frame-Options "" always;
    add_header Content-Security-Policy "frame-ancestors 'self' https://midia.agenciasaved.com.br" always;
  }
}
